name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t danujan06/spring_app .
      - name: Push Docker Image
        run: docker push danujan06/spring_app:latest
  deploy:
    needs: build
    runs-on: aws-ec2-backend
    steps:
      - name: Pull image from docker hub
        run: docker pull danujan06/spring_app:latest 
      - name: Delete Old Container
        run: docker rm -f springContainer
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springContainer danujan06/spring_app



  